
<form role="form" action="/usuario/add" id="UsuarioAdd" method="post" >

  <div class="form-group">
    <label>Clave</label>
    <input type="text" class="form-control" id="clave"  name="clave">
  </div>
  <div class="form-group">
    <label>Nombre</label>
    <input type="text" class="form-control" id="nombre" name="nombre">
  </div>
  <div class="form-group">
    <label>Calificacion</label>
    <input type="text" class="form-control" id="calificaciones" name="calificaciones" >
  </div>
  
  
  <button type="submit" class="btn btn-default">Alta</button>
</form>