
<form role="form" action="/usuario/edit" id="UsuarioEdit" method="post" >

<input type="hidden" name="clave" name="clave" value=<?php echo $this->datos['clave']?>>
  <div class="form-group">
    <label>Nombre</label>
    <input type="text" class="form-control" id="nombre"  name="nombre" placeholder="<?php echo $this->datos['nombre']?>">
  </div>
  <div class="form-group">
    <label>Calificacion</label>
    <input type="text" class="form-control" id="calificaciones" name="calificaciones" placeholder="<?php echo $this->datos['calificaciones']?>">
  </div>  
  
  <button type="submit" class="btn btn-default">Guardar</button>
</form>